### ISSUE TITLE
sd-buddy overrides an old image with a new image if you leave it selected in Finder

### ISSUE THREAD

**Issue by sw-yx** [breadthe/sd-buddy#13]
repro steps

1. generate an image
2. open in finder, select it with your mouse, leave it selected, tab back to sd-buddy
3. generate another image

the new image will use the old filename and override the old image

**Comment by sw-yx** [comment]
not sure its sd-buddy's fault but just logging the bug

**Comment by breadthe** [comment]
I can't reproduce it, but I have another suspicion. Did you, by any chance, delete any images from the output location? I think it's the python command which does that even without SD Buddy. It tries to fill any gaps left in the image name sequence but it overwrites them in the process.

**Comment by sw-yx** [comment]
yes i did delete images from the output location!

**Comment by sw-yx** [comment]
gonna close this for now but feel free to reopen if you think its a major issue.. i kinda wanna keep my output folder clean

**Comment by breadthe** [comment]
I'm 99% sure it's a bug in the python script. I'm not a python dev so it's not a huge priority right now but I'll take a look at it one day when the workload is less. The workaround until then is not to delete any images from disk. Not at all ideal, but at least I have the app to keep track of the ones I like.
