### ISSUE TITLE
Theme broken when system is in dark mode and the light theme is selected

### ISSUE THREAD

**Issue by 2xAA** [breadthe/sd-buddy#25]
<img width="1412" alt="Screenshot 2022-10-01 at 20 42 49" src="https://user-images.githubusercontent.com/554219/193425699-ba9d5d7b-57e9-403c-a092-8c488cfb75cc.png">

My system (macOS 12.5.1, MacBook Pro (16-inch, 2021)) is in dark mode, SD Buddy's theme doesn't work properly when using the light theme.

Works fine when using dark theme or follow OS preference.
Also works fine if the system is in light mode and SD Buddy's theme is dark.

**Comment by breadthe** [comment]
Good catch! I admit I didn't test this particular scenario.

**Comment by breadthe** [comment]
Fixed in [v0.9.1](https://github.com/breadthe/sd-buddy/releases/tag/v0.9.1)
